---
title: "Creating graphs in R with 'ggplot2'"
author: "trobinson"
date: "11/19/2020"
output: html_document
---

# Plots with ggplot2

We are going to make plots in R and it's going to be amazing.

```{r}
library(tidyverse)
library(readxl)
library(here)
```

```{r}
ca_np <- read_csv(here("data", "ca_np.csv"))
```

```{r}
ci_np <- read_excel(here("data", "ci_np.xlsx"))
```

```{r}
summary(ci_np)
```

```{r}
ggplot(data = ci_np, aes(x = year, y = visitors)) +
  geom_line()
```

```{r}
gg_base <- ggplot(data = ci_np, aes(x= year, y = visitors))
```

```{r}
gg_base +
  geom_line(
  colour = "purple", 
  linetype = "dotted"
  )
```

```{r}
gg_base +
  geom_point(
    aes(color = visitors, 
    size = visitors),
    alpha = 0.5
  ) +
  theme_light()
```


```{r}
gg_base +
  geom_col(
    aes(
      fill=visitors)
    
  )
```


``` {r}
gg_base +
  geom_line(linetype = "dotted") +
  theme_bw() +
  labs(
    x="Year",
    y="Annual park visitors",
    title = "Channel Islands NP Visitation",
    subtitle = "(1963-2016)"
  )






```
``` {r}
gg_base +
  geom_line(color = "Purple") +
  geom_point(color = "orange",
    aes(size = year),
    alpha = 0.5)
```
``` {r}
names(ca_np)
```


``` {r}
ggplot(data = ca_np, aes(x=year, y = visitors, group = park_name)) +
          geom_line(aes(color=park_name))
```
``` {r}
gg_np <- ggplot(data = ca_np, aes(x=year, y = visitors, group = park_name))

```

``` {r}
gg_np +
  geom_line(show.legend = FALSE) +
  theme_light() + 
  labs(x = "year", y = "annual visitors") +
  facet_wrap(~ park_name)
```

``` {r}
ggsave(here("figures", "np_graph.jpg"), dpi=180, width = 8, height = 7)
```

